import { Jaldi } from "next/font/google";
import "./globals.css";

export const jaldi = Jaldi({ weight: ["400", "700"] subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jaldi.className}>{children}</body>
    </html>
  );
}
